config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  #defines which action handles the route page
  root "books#index"

  #creates actions index, create, new, edit, show, update
  resources :books

  #add route so i can render a view before delete method call
  get '/books/:id/remove', to: 'books#remove', as: 'remove_book'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

    validates :title, presence: true
    validates :author, presence: true
    validates :genre, presence: true
    validates :price, presence: true
    validates :published_date, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

    def index
        @books = Book.all
    end

    #show assigns @book to the Book that was clicked on.
    #it finds it by pulling the id from the uri path
    def show
        @book = Book.find(params[:id])
    end

    #instantiates a new book object but does not save it to db.
    #presents the form to the user
    def new
        @book = Book.new
    end

    #instantiates and saves a book with data from the input form.
    def create
        @book_params = params[:book]
        @date = Date.new(@book_params["published_date(1i)"].to_i, @book_params["published_date(2i)"].to_i, @book_params["published_date(3i)"].to_i)
        @book = Book.new(title: @book_params[:title], author: @book_params[:author], genre: @book_params[:genre], price: @book_params[:price], published_date: @date)
    
        if @book.save
            redirect_to root_path, notice: "The book \"#{@book.title}\" has been ADDED!"
        else
            render :new
        end
    end

    #when upating a book, fetch the book and present a form
    def edit
        @book = Book.find(params[:id])
    end

    #try to save the form from the edit action if it does go to the details of the book
    def update
        @book_params = params[:book]
        @book = Book.find(params[:id])
        @date = Date.new(@book_params["published_date(1i)"].to_i, @book_params["published_date(2i)"].to_i, @book_params["published_date(3i)"].to_i)

        if @book.update(title: @book_params[:title], author: @book_params[:author], genre: @book_params[:genre], price: @book_params[:price], published_date: @date)
            redirect_to root_path, notice: "The book \"#{@book.title}\" has been UPDATED!"
        else
            render :edit
        end
    end

    #present the user with a page to confirm deletion
    def remove
        @book = Book.find(params[:id])
    end

    #actually remove the book
    def destroy
        @book = Book.find(params[:id])
        @book.destroy

        redirect_to root_path, notice: "The book \"#{@book.title}\" has been REMOVED!"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/edit.html.erb
<div class="center">
    <h1>Edit Book</h1>

    <%= form_with model: @book do |form| %>
        <div class="formElement">
            <%= form.label :title, "Title" %>
            <br>
            <%= form.text_field :title %>
            <% @book.errors.full_messages_for(:title).each do |message| %>
                <div><%= message %></div>
            <% end %>
        </div>
        <div class="formElement">
            <%= form.label :author, "Author" %>
            <br>
            <%= form.text_field :author %>
            <% @book.errors.full_messages_for(:author).each do |message| %>
                <div><%= message %></div>
            <% end %>
        </div>
        <div class="formElement">
            <%= form.label :genre, "Genre" %>
            <br>
            <%= form.select :genre, ['Action', 'Adventure', "Biography", "Drama", "Fantasy", "Mystery", "Romance", "Thriller"] %>
            <% @book.errors.full_messages_for(:genre).each do |message| %>
                <div><%= message %></div>
            <% end %>
        </div>
        <div class="formElement">
            <%= form.label :price, "Price" %>
            <br>
            <%= form.number_field :price, in: 0.0..50.0, step: 1.0 %>
            <% @book.errors.full_messages_for(:price).each do |message| %>
                <div><%= message %></div>
            <% end %>
        </div>
        <div class="formElement">
            <%= form.label :published_date, "Date Published" %>
            <br>
            <%= form.date_select :published_date, {order: [:month, :day, :year], start_year: 1990, end_year: 2020} %>
            <% @book.errors.full_messages_for(:published_date).each do |message| %>
                <div><%= message %></div>
            <% end %>
        </div>
        <div class="formElement">
            <%= form.submit "Save Edit" %>
        </div>
    <% end %>

    <%= link_to "Home", root_path %>
</div>

app/views/books/index.html.erb
<%= stylesheet_link_tag "global" %>

<div class="center">
    <h1>Book Collection</h1>

    <% flash.each do |type, msg| %>
        <div class="notice"><%= msg %></div>
    <% end %>

    <div class="indexTable">
        <table class="table">
            <tr>
                <th>Title</th>
                <th>Author</th>
                <th>Action</th>
            </tr>
            <% @books.each do |book| %>
                <tr>
                    <td><%= link_to book.title, book %></td>
                    <td><%= book.author %></td>
                    <td><%= link_to "Edit", edit_book_path(book) %> - <%= link_to "Remove", remove_book_path(book) %></td>
                </tr>
            <% end %>
            <tr>
                <td><%= link_to "+", new_book_path %></td>
            </tr>
        <table>
    </div>
</div>

app/views/books/new.html.erb
<div class="center">
    <h1>Add Book</h1>

    <%= form_with model: @book do |form| %>
        <div class="formElement">
            <%= form.label :title, "Title" %>
            <br>
            <%= form.text_field :title %>
            <% @book.errors.full_messages_for(:title).each do |message| %>
            <div><%= message %></div>
            <% end %>
        </div>
        <div class="formElement">
            <%= form.label :author, "Author" %>
            <br>
            <%= form.text_field :author %>
            <% @book.errors.full_messages_for(:author).each do |message| %>
                <div><%= message %></div>
            <% end %>
        </div>
        <div class="formElement">
            <%= form.label :genre, "Genre" %>
            <br>
            <%= form.select :genre, ['Action', 'Adventure', "Biography", "Drama", "Fantasy", "Mystery", "Romance", "Thriller"] %>
            <% @book.errors.full_messages_for(:genre).each do |message| %>
                <div><%= message %></div>
            <% end %>
        </div>
        <div class="formElement">
            <%= form.label :price, "Price" %>
            <br>
            <%= form.number_field :price, in: 0.0..50.0, step: 1.0 %>
            <% @book.errors.full_messages_for(:price).each do |message| %>
                <div><%= message %></div>
            <% end %>
        </div>
        <div class="formElement">
            <%= form.label :published_date, "Date Published" %>
            <br>
            <%= form.date_select :published_date, {order: [:month, :day, :year], start_year: 1990, end_year: 2020, prompt: {month: "Select Month", day: "Select Day", year: "Select Year"}} %>
            <% @book.errors.full_messages_for(:published_date).each do |message| %>
                <div><%= message %></div>
            <% end %>
        </div>
        <div class="formElement">
            <%= form.submit "Add Book" %>
        </div>
    <% end %>

    <%= link_to "Home", root_path %>
</div>

app/views/books/remove.html.erb
<div class="center">
    <h1>Remove Book</h1>

        <ul>
            <p><b>Title:</b> <%= @book.title %></p>
            <br>
            <p><b>Author:</b> <%= @book.author %></p>
            <br>
            <p><b>Genre:</b> <%= @book.genre %></p>
            <br>
            <p><b>Price:</b> $<%= @book.price %></p>
            <br>
            <p><b>Published Date (Year-Month-Day):</b> <%= @book.published_date.to_s.split(" ")[0] %></p>
        </ul>

    <%= button_to "Remove Book", book_path(@book), method: :delete, data: { confirm: "Confirm Removal?" } %>
    <br>
    <%= link_to "Home", root_path %>
</div>

app/views/books/show.html.erb
<div class="center">
    <h1>Book Details</h1>

    <ul>
        <p><b>Title:</b> <%= @book.title %></p>
        <br>
        <p><b>Author:</b> <%= @book.author %></p>
        <br>
        <p><b>Genre:</b> <%= @book.genre %></p>
        <br>
        <p><b>Price:</b> $<%= @book.price %></p>
        <br>
        <p><b>Published Date (Year-Month-Day):</b> <%= @book.published_date.to_s.split(" ")[0] %></p>
    </ul>

    <div class="horozontal">
        <%= link_to "Edit", edit_book_path(@book), class: "showLink" %>
        <%= link_to "Remove", remove_book_path(@book), class: "showLink" %>
        <%= link_to "Home", root_path, class: "showLink" %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookCollection</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>